#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute. 

python train_MAML_4split.py
python test_DRD.py
python PLOT.py
